version: '3.4'

networks:
    network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.33.0.0/16

volumes:
  export: {}
  data: {}
  
services:
  ipfs.dnp.dappnode.eth:
    build: ./build
    image: ipfs.dnp.dappnode.eth:0.1.0
    container_name: DAppNodeCore-ipfs.dnp.dappnode.eth
    volumes:
      - export:/export
      - data:/data/ipfs
    ports:
      - 4001:4001
      - 4002:4002/udp
    dns: 172.33.1.2
    networks:
      network:
        ipv4_address: 172.33.1.5
