version: '3.4'
networks:
    network:
        driver: bridge
        ipam:
            config:
                -
                    subnet: 172.33.0.0/16
volumes:
    ipfsdnpdappnodeeth_export: {}
    ipfsdnpdappnodeeth_data: {}
services:
    ipfs.dnp.dappnode.eth:
        build: ./build
        image: 'ipfs.dnp.dappnode.eth:0.1.4'
        container_name: DAppNodeCore-ipfs.dnp.dappnode.eth
        restart: always
        volumes:
            - 'ipfsdnpdappnodeeth_export:/export'
            - 'ipfsdnpdappnodeeth_data:/data/ipfs'
        ports:
            - '4001:4001'
            - '4002:4002/udp'
        env_file:
            - ipfs.dnp.dappnode.eth.env
        dns: 172.33.1.2
        networks:
            network:
                ipv4_address: 172.33.1.5
        logging:
            options:
                max-size: "10m"
                max-file: "3"
