name: "Main"
on:
  repository_dispatch:
  pull_request:
  push:
    branches:
      - "master"
      - "v[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "README.md"

jobs:
  fs-repo-migration-test:
    runs-on: ubuntu-latest
    name: IPFS File system migration
    steps:
      - uses: actions/checkout@v2
      - run: ./test/test-migrations/fs-repo-migration.sh

  integration-test:
    runs-on: ubuntu-16.04
    name: Integration tests
    steps:
      - uses: actions/checkout@v2
      - run: ./test/test-ipfs-commands/test.sh

  build-test:
    runs-on: ubuntu-latest
    name: Build test
    if: github.event_name != 'push'
    steps:
      - uses: actions/checkout@v2
      - run: npx @dappnode/dappnodesdk build --skip_save

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: npx @dappnode/dappnodesdk publish patch --dappnode_team_preset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0xf35960302a07022aba880dffaec2fdd64d5bf1c1"
